# Generated by Django 4.1.5 on 2023-05-23 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APP_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('APP_SECRET', models.CharField(blank=True, max_length=200, null=True)),
                ('ACCESS_TOKEN', models.CharField(blank=True, max_length=400, null=True)),
                ('LONGLIVED_ACCESS_TOKEN', models.CharField(blank=True, max_length=400, null=True)),
                ('has_app_key', models.BooleanField(default=False)),
                ('has_access_token', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
