# Generated by Django 4.1.5 on 2023-05-25 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook', '0002_alter_creds_access_token_alter_creds_app_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=50, null=True)),
                ('page_access_token', models.CharField(blank=True, max_length=400, null=True)),
                ('longlived_access_token', models.CharField(blank=True, max_length=400, null=True)),
                ('has_access_token', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
