# Generated by Django 4.1.5 on 2023-05-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_adaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccounts',
            name='page_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
