# Generated by Django 4.1.5 on 2023-05-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_adaccounts_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccounts',
            name='longlived_access_token',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adaccounts',
            name='page_access_token',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adaccounts',
            name='page_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adaccounts',
            name='page_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
