# Generated by Django 4.1.5 on 2023-05-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_alter_adaccounts_longlived_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('page_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('page_access_token', models.CharField(blank=True, max_length=400, null=True, unique=True)),
                ('longlived_access_token', models.CharField(blank=True, max_length=400, null=True, unique=True)),
                ('has_access_token', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='adaccounts',
            name='has_access_token',
        ),
        migrations.RemoveField(
            model_name='adaccounts',
            name='longlived_access_token',
        ),
        migrations.RemoveField(
            model_name='adaccounts',
            name='page_access_token',
        ),
        migrations.RemoveField(
            model_name='adaccounts',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='adaccounts',
            name='page_name',
        ),
        migrations.AddField(
            model_name='adaccounts',
            name='ad_account_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adaccounts',
            name='ad_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adaccounts',
            name='page_associated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook.accountpages'),
        ),
    ]
