# Generated by Django 4.1.5 on 2023-05-29 14:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook', '0006_accountpages_remove_adaccounts_has_access_token_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdAccounts',
            new_name='AccountsAd',
        ),
        migrations.AlterModelOptions(
            name='accountpages',
            options={'verbose_name_plural': 'Account Pages'},
        ),
        migrations.AlterModelOptions(
            name='accountsad',
            options={'verbose_name_plural': 'Account Ads'},
        ),
        migrations.AlterModelOptions(
            name='creds',
            options={'verbose_name_plural': 'Credentials'},
        ),
    ]
