# Generated by Django 4.1.5 on 2023-05-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0007_rename_adaccounts_accountsad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpages',
            name='longlived_access_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='accountpages',
            name='page_access_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='accountpages',
            name='page_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
