# Generated by Django 4.1.5 on 2023-06-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0010_accountpages_user_alter_accountsad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='creds',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
