# Generated by Django 4.2.2 on 2023-07-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0012_accountsad_is_priority_ignoredcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsad',
            name='access_token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
