# Generated by Django 4.2.2 on 2023-08-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0014_emailmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsad',
            name='is_priority',
        ),
        migrations.DeleteModel(
            name='EmailModel',
        ),
    ]
