# Generated by Django 4.2.2 on 2023-08-04 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook', '0015_remove_accountsad_is_priority_delete_emailmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogNegativeComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_id', models.CharField(max_length=100)),
                ('ad_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ad_id', models.CharField(blank=True, max_length=100, null=True)),
                ('adset_name', models.CharField(blank=True, max_length=100, null=True)),
                ('adset_id', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('is_mail_sent', models.BooleanField(default=False)),
                ('automation_runtime', models.DateTimeField(blank=True, null=True)),
                ('adaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.accountsad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
