# Generated by Django 4.2.2 on 2023-08-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lognegativecomments',
            name='created_date',
        ),
        migrations.AddField(
            model_name='lognegativecomments',
            name='created_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
