# Generated by Django 4.2.2 on 2023-08-05 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0015_remove_accountsad_is_priority_delete_emailmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automation', '0002_remove_lognegativecomments_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPositiveComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_count', models.IntegerField(default=0)),
                ('campaign_id', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=100, null=True)),
                ('adset_id', models.CharField(blank=True, max_length=100, null=True)),
                ('adset_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ad_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ad_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_time', models.DateField(blank=True, null=True)),
                ('is_mail_sent', models.BooleanField(default=False)),
                ('automation_runtime', models.TimeField(blank=True, null=True)),
                ('adaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.accountsad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
