# Generated by Django 4.2.2 on 2023-08-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_logpositivecomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lognegativecomments',
            options={'verbose_name_plural': 'Log Negative Comments'},
        ),
        migrations.AlterModelOptions(
            name='logpositivecomments',
            options={'verbose_name_plural': 'Log Positive Comments'},
        ),
        migrations.AlterField(
            model_name='logpositivecomments',
            name='created_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
