# Generated by Django 4.2.2 on 2023-08-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_alter_lognegativecomments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lognegativecomments',
            name='automation_runtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='logpositivecomments',
            name='automation_runtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
